version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: nestjs_template_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestjs_template
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 